/* Generated by automated build script */
#define RELEASE 0.10
#define TEXTVER "Release 0.10"
#define SSHVER "Cpshell-Release-0.10"
#define BINARY_VERSION 0,10,0,0
#define SOURCE_COMMIT "3cd10509a51edf5a21cdc80aabf7e6a934522d47"
